name: Docker Build and Extract Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t goscheduler-builder .

      - name: Extract built binary from Docker image
        run: |
          container_id=$(docker create goscheduler-builder)
          docker cp $container_id:/app/goscheduler ./goscheduler
          docker rm -v $container_id

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: goscheduler
          path: ./goscheduler
